# Generated by Django 3.2.7 on 2021-09-06 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField(validators=[django.core.validators.MinValueValidator(19), django.core.validators.MaxValueValidator(28)])),
                ('humidity', models.FloatField(validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(65)])),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
