# Generated by Django 3.2.7 on 2021-09-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='end_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='summary',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
