# Generated by Django 3.2.7 on 2021-09-06 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20210906_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summary',
            old_name='end_data',
            new_name='end_date',
        ),
    ]
